/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "ESP32 Garden Irrigation System": {
        "en": "ESP32 Garden Irrigation System",
        "de": "ESP32 Gartenbewässerungssystem",
        "ru": "Система полива сада ESP32",
        "pt": "Sistema de Irrigação de Jardim ESP32",
        "nl": "ESP32 Tuin Irrigatiesysteem",
        "fr": "Système d'irrigation de jardin ESP32",
        "it": "Sistema di irrigazione del giardino ESP32",
        "es": "Sistema de riego de jardín ESP32",
        "pl": "System nawadniania ogrodu ESP32",
        "zh-cn": "ESP32花园灌溉系统"
    },
    "This adapter connects to your ESP32-based garden irrigation system and provides all sensor data, status information, and control functions as ioBroker states.": {
        "en": "This adapter connects to your ESP32-based garden irrigation system and provides all sensor data, status information, and control functions as ioBroker states.",
        "de": "Dieser Adapter verbindet sich mit Ihrem ESP32-basierten Gartenbewässerungssystem und stellt alle Sensordaten, Statusinformationen und Steuerfunktionen als ioBroker-States zur Verfügung.",
        "ru": "Этот адаптер подключается к вашей системе полива сада на базе ESP32 и предоставляет все данные датчиков, информацию о состоянии и функции управления в виде состояний ioBroker.",
        "pt": "Este adaptador conecta-se ao seu sistema de irrigação de jardim baseado em ESP32 e fornece todos os dados do sensor, informações de status e funções de controle como estados do ioBroker.",
        "nl": "Deze adapter verbindt met uw ESP32-gebaseerde tuinirrigatiesysteem en biedt alle sensorgegevens, statusinformatie en besturingsfuncties als ioBroker-toestanden.",
        "fr": "Cet adaptateur se connecte à votre système d'irrigation de jardin basé sur ESP32 et fournit toutes les données de capteur, informations d'état et fonctions de contrôle en tant qu'états ioBroker.",
        "it": "Questo adattatore si collega al tuo sistema di irrigazione del giardino basato su ESP32 e fornisce tutti i dati del sensore, le informazioni di stato e le funzioni di controllo come stati ioBroker.",
        "es": "Este adaptador se conecta a su sistema de riego de jardín basado en ESP32 y proporciona todos los datos del sensor, información de estado y funciones de control como estados de ioBroker.",
        "pl": "Ten adapter łączy się z systemem nawadniania ogrodu opartym na ESP32 i zapewnia wszystkie dane czujników, informacje o stanie i funkcje kontroli jako stany ioBroker.",
        "zh-cn": "此适配器连接到您基于ESP32的花园灌溉系统，并将所有传感器数据、状态信息和控制功能作为ioBroker状态提供。"
    },
    "Connection Settings": {
        "en": "Connection Settings",
        "de": "Verbindungseinstellungen",
        "ru": "Настройки подключения",
        "pt": "Configurações de Conexão",
        "nl": "Verbindingsinstellingen",
        "fr": "Paramètres de connexion",
        "it": "Impostazioni di connessione",
        "es": "Configuración de conexión",
        "pl": "Ustawienia połączenia",
        "zh-cn": "连接设置"
    },
    "ESP32 IP Address": {
        "en": "ESP32 IP Address",
        "de": "ESP32 IP-Adresse",
        "ru": "IP-адрес ESP32",
        "pt": "Endereço IP ESP32",
        "nl": "ESP32 IP-adres",
        "fr": "Adresse IP ESP32",
        "it": "Indirizzo IP ESP32",
        "es": "Dirección IP ESP32",
        "pl": "Adres IP ESP32",
        "zh-cn": "ESP32 IP地址"
    },
    "IP address of your ESP32 irrigation system": {
        "en": "IP address of your ESP32 irrigation system",
        "de": "IP-Adresse Ihres ESP32 Bewässerungssystems",
        "ru": "IP-адрес вашей системы орошения ESP32",
        "pt": "Endereço IP do seu sistema de irrigação ESP32",
        "nl": "IP-adres van uw ESP32 irrigatiesysteem",
        "fr": "Adresse IP de votre système d'irrigation ESP32",
        "it": "Indirizzo IP del tuo sistema di irrigazione ESP32",
        "es": "Dirección IP de su sistema de riego ESP32",
        "pl": "Adres IP systemu nawadniania ESP32",
        "zh-cn": "您的ESP32灌溉系统的IP地址"
    },
    "Port": {
        "en": "Port",
        "de": "Port",
        "ru": "Порт",
        "pt": "Porta",
        "nl": "Poort",
        "fr": "Port",
        "it": "Porta",
        "es": "Puerto",
        "pl": "Port",
        "zh-cn": "端口"
    },
    "HTTP port (usually 80)": {
        "en": "HTTP port (usually 80)",
        "de": "HTTP-Port (normalerweise 80)",
        "ru": "HTTP-порт (обычно 80)",
        "pt": "Porta HTTP (geralmente 80)",
        "nl": "HTTP-poort (meestal 80)",
        "fr": "Port HTTP (généralement 80)",
        "it": "Porta HTTP (di solito 80)",
        "es": "Puerto HTTP (generalmente 80)",
        "pl": "Port HTTP (zwykle 80)",
        "zh-cn": "HTTP端口（通常为80）"
    },
    "Username": {
        "en": "Username",
        "de": "Benutzername",
        "ru": "Имя пользователя",
        "pt": "Nome de usuário",
        "nl": "Gebruikersnaam",
        "fr": "Nom d'utilisateur",
        "it": "Nome utente",
        "es": "Nombre de usuario",
        "pl": "Nazwa użytkownika",
        "zh-cn": "用户名"
    },
    "Login username for ESP32 web interface": {
        "en": "Login username for ESP32 web interface",
        "de": "Login-Benutzername für ESP32-Webinterface",
        "ru": "Имя пользователя для входа в веб-интерфейс ESP32",
        "pt": "Nome de usuário de login para interface web ESP32",
        "nl": "Inlog gebruikersnaam voor ESP32 webinterface",
        "fr": "Nom d'utilisateur de connexion pour l'interface web ESP32",
        "it": "Nome utente di accesso per l'interfaccia web ESP32",
        "es": "Nombre de usuario de inicio de sesión para la interfaz web ESP32",
        "pl": "Nazwa użytkownika logowania dla interfejsu web ESP32",
        "zh-cn": "ESP32网络界面登录用户名"
    },
    "Password": {
        "en": "Password",
        "de": "Passwort",
        "ru": "Пароль",
        "pt": "Senha",
        "nl": "Wachtwoord",
        "fr": "Mot de passe",
        "it": "Password",
        "es": "Contraseña",
        "pl": "Hasło",
        "zh-cn": "密码"
    },
    "Login password for ESP32 web interface": {
        "en": "Login password for ESP32 web interface",
        "de": "Login-Passwort für ESP32-Webinterface",
        "ru": "Пароль для входа в веб-интерфейс ESP32",
        "pt": "Senha de login para interface web ESP32",
        "nl": "Inlog wachtwoord voor ESP32 webinterface",
        "fr": "Mot de passe de connexion pour l'interface web ESP32",
        "it": "Password di accesso per l'interfaccia web ESP32",
        "es": "Contraseña de inicio de sesión para la interfaz web ESP32",
        "pl": "Hasło logowania dla interfejsu web ESP32",
        "zh-cn": "ESP32网络界面登录密码"
    },
    "Update Settings": {
        "en": "Update Settings",
        "de": "Update-Einstellungen",
        "ru": "Настройки обновления",
        "pt": "Configurações de Atualização",
        "nl": "Update-instellingen",
        "fr": "Paramètres de mise à jour",
        "it": "Impostazioni di aggiornamento",
        "es": "Configuración de actualización",
        "pl": "Ustawienia aktualizacji",
        "zh-cn": "更新设置"
    },
    "Update Interval (seconds)": {
        "en": "Update Interval (seconds)",
        "de": "Update-Intervall (Sekunden)",
        "ru": "Интервал обновления (секунды)",
        "pt": "Intervalo de Atualização (segundos)",
        "nl": "Update-interval (seconden)",
        "fr": "Intervalle de mise à jour (secondes)",
        "it": "Intervallo di aggiornamento (secondi)",
        "es": "Intervalo de actualización (segundos)",
        "pl": "Interwał aktualizacji (sekundy)",
        "zh-cn": "更新间隔（秒）"
    },
    "How often to poll the ESP32 for new data (5-3600 seconds)": {
        "en": "How often to poll the ESP32 for new data (5-3600 seconds)",
        "de": "Wie oft das ESP32 nach neuen Daten abgefragt werden soll (5-3600 Sekunden)",
        "ru": "Как часто опрашивать ESP32 на предмет новых данных (5-3600 секунд)",
        "pt": "Com que frequência sondar o ESP32 para novos dados (5-3600 segundos)",
        "nl": "Hoe vaak de ESP32 bevragen voor nieuwe gegevens (5-3600 seconden)",
        "fr": "À quelle fréquence interroger l'ESP32 pour de nouvelles données (5-3600 secondes)",
        "it": "Quanto spesso interrogare l'ESP32 per nuovi dati (5-3600 secondi)",
        "es": "Con qué frecuencia sondear el ESP32 para nuevos datos (5-3600 segundos)",
        "pl": "Jak często odpytywać ESP32 o nowe dane (5-3600 sekund)",
        "zh-cn": "多久轮询ESP32获取新数据（5-3600秒）"
    },
    "Test Connection": {
        "en": "Test Connection",
        "de": "Verbindung testen",
        "ru": "Тест соединения",
        "pt": "Testar Conexão",
        "nl": "Verbinding testen",
        "fr": "Tester la connexion",
        "it": "Testa connessione",
        "es": "Probar conexión",
        "pl": "Testuj połączenie",
        "zh-cn": "测试连接"
    },
    "Click to test the connection to your ESP32 system": {
        "en": "Click to test the connection to your ESP32 system",
        "de": "Klicken Sie, um die Verbindung zu Ihrem ESP32-System zu testen",
        "ru": "Нажмите, чтобы проверить соединение с вашей системой ESP32",
        "pt": "Clique para testar a conexão com seu sistema ESP32",
        "nl": "Klik om de verbinding met uw ESP32-systeem te testen",
        "fr": "Cliquez pour tester la connexion à votre système ESP32",
        "it": "Clicca per testare la connessione al tuo sistema ESP32",
        "es": "Haga clic para probar la conexión a su sistema ESP32",
        "pl": "Kliknij, aby przetestować połączenie z systemem ESP32",
        "zh-cn": "点击测试与ESP32系统的连接"
    },
    "Available States": {
        "en": "Available States",
        "de": "Verfügbare States",
        "ru": "Доступные состояния",
        "pt": "Estados Disponíveis",
        "nl": "Beschikbare toestanden",
        "fr": "États disponibles",
        "it": "Stati disponibili",
        "es": "Estados disponibles",
        "pl": "Dostępne stany",
        "zh-cn": "可用状态"
    },
    "After successful connection, the following state structure will be created:": {
        "en": "After successful connection, the following state structure will be created:",
        "de": "Nach erfolgreicher Verbindung wird folgende State-Struktur erstellt:",
        "ru": "После успешного подключения будет создана следующая структура состояний:",
        "pt": "Após conexão bem-sucedida, a seguinte estrutura de estado será criada:",
        "nl": "Na succesvolle verbinding wordt de volgende toestandsstructuur gemaakt:",
        "fr": "Après une connexion réussie, la structure d'état suivante sera créée:",
        "it": "Dopo una connessione riuscita, verrà creata la seguente struttura di stati:",
        "es": "Después de una conexión exitosa, se creará la siguiente estructura de estado:",
        "pl": "Po pomyślnym połączeniu zostanie utworzona następująca struktura stanów:",
        "zh-cn": "连接成功后，将创建以下状态结构："
    }
};